builds:
  - binary: md4pt
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      amd64: x86_64
      386: i386
      darwin: Darwin
      linux: Linux
      windows: Window
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - README_JA.md
      - LICENCE.txt